# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
 vmImage: ubuntu-latest
 
variables:
 imageName: taskmanagerapp
 imageTag: latest

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
     packageType : 'sdk'
     version: '9.0.x'
     

  - script: dotnet restore
    displayName: 'Restore dependebcies'
  
  - script: dotnet build --configuration Release
    displayName: 'Build .Net Project'

  # - script: dotet test --no-build --verbosity normal
  #   displayName: 'Run Tests'

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      Dockerfile: '$(Build.SourceDirectory)/Dockerfile'
      tags: |
       $(imagename):$(imageName)

  
      